"""add poster_url to jobs

Revision ID: c217824d6f1b
Revises: 8b9c0fe3c95f
Create Date: 2026-08-22 03:03:37.786727
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c217824d6f1b'
down_revision: Union[str, None] = '8b9c0fe3c95f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('poster_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'poster_url')
    # ### end Alembic commands ###
