/**
 * Section 4 — footer. Four plain columns, then the wordmark set large enough
 * to run the full width and clip at the baseline, echoing the reference.
 */

const QUICK_LINKS = [
  { label: "Home", href: "/" },
  { label: "Library", href: "/library" },
  { label: "Showcase", href: "/#showcase" },
  { label: "About", href: "/#about" },
  { label: "Contact", href: "/#contact" },
];

const SOCIAL = ["Twitter", "GitHub", "YouTube", "Discord"];

export function SiteFooter() {
  return (
    <footer id="contact" className="bg-ink pt-24 sm:pt-32">
      <div className="mx-auto max-w-6xl px-6">
        <div className="grid grid-cols-2 gap-x-8 gap-y-12 md:grid-cols-4">
          <div>
            <p className="tag mb-5 text-paper-600">Sitemap</p>
            <ul className="space-y-2">
              {QUICK_LINKS.map((link) => (
                <li key={link.label}>
                  <a
                    href={link.href}
                    className="text-sm font-medium text-paper transition-colors hover:text-paper"
                  >
                    {link.label}
                  </a>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <p className="tag mb-5 text-paper-600">Social</p>
            <ul className="space-y-2">
              {SOCIAL.map((name) => (
                <li key={name}>
                  <a
                    href="#"
                    className="text-sm font-medium text-paper transition-colors hover:text-paper"
                  >
                    {name}
                  </a>
                </li>
              ))}
            </ul>
          </div>

          <div id="about">
            <p className="tag mb-5 text-paper-600">Contact</p>
            <p className="text-sm font-medium leading-relaxed text-paper">
              Questions, bugs, or something you made that we should see —
              open an issue on GitHub and we&apos;ll pick it up there.
            </p>
          </div>

          <div>
            <p className="tag mb-5 text-paper-600">Explore</p>
            <a
              href="/library"
              className="text-sm font-medium text-highlight/80 transition-colors hover:text-highlight"
            >
              Browse examples
            </a>
            <p className="mt-5 max-w-[22ch] text-sm font-medium leading-relaxed text-paper-400">
              Describe a concept in plain language and get back a narrated
              animation, rendered with Manim.
            </p>
          </div>
        </div>

        <div className="mt-20 flex flex-col gap-2 border-t border-paper/10 pt-6 text-[11px] text-paper-600 sm:flex-row sm:items-center sm:justify-between">
          <p>© 2026 2DAnimator</p>
          <p>Animations rendered with Manim · Narration and code generated by AI</p>
        </div>
      </div>

      {/* Wordmark. Clipped at the baseline so it reads as a mark, not a line
          of copy. */}
      <div className="mt-14 overflow-hidden px-4">
        <p
          aria-hidden="true"
          className="-mb-[0.18em] whitespace-nowrap text-center font-display font-bold leading-[0.8] text-paper"
          style={{ fontSize: "clamp(3.4rem, 15.5vw, 15rem)" }}
        >
          2DAnimator
        </p>
      </div>
    </footer>
  );
}
